#!/bin/bash

gemfile_dir=$1
gemfile="$gemfile_dir/Gemfile"

echo
echo "Testing with $gemfile..."
cd $gemfile_dir
bundle update
result="$(bundle exec cucumber --strict --require code ../features)"

status=$?
if [[ $status -ne 0 ]]; then
  echo 
  echo "=> FAIL: Expected zero exit status"
  echo
  echo "Output was:"
  echo "--"
  echo "$result"
  echo "--"
  cd -
  exit 1
fi
echo "=> PASS"
cd -

