#!/bin/bash

gemfile_dir=$1
gemfile="$gemfile_dir/Gemfile"
gemfile_code_dir="$gemfile_dir/code"

echo
echo "Testing with $gemfile..."
export BUNDLE_GEMFILE=$gemfile
bundle update
result="$(bundle exec cucumber --strict --require $gemfile_code_dir test/features)"

status=$?
if [[ $status -ne 0 ]]; then
  echo 
  echo "=> FAIL: Expected zero exit status"
  echo
  echo "Output was:"
  echo "--"
  echo "$result"
  echo "--"
  exit 1
fi
echo "=> PASS"

